name = "cloudflare-chat"
main = "dist/index.mjs"
compatibility_date = "2022-11-23"

[durable_objects]
bindings = [{ name = "MY_DURABLE_OBJECT", class_name = "DurableObjectExample" }]

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectExample"] 

[build]
command = "npm run build"