name = "cloudflare-chat"
main = "./dist/index.mjs"
compatibility_date = "2022-11-23"

[durable_objects]
bindings = [
  { name = "CHANNELS", class_name = "ChannelsDO" },
  { name = "CHANNEL", class_name = "ChannelDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChannelsDO"]

[build]
command = "npm run build"